#!/bin/env bash

set -e

nvim -u tests/minit.lua --headless +'lua require("snacks.docs").build()' +qa

echo -e "\n\nGenerating Vim Help"

if [ "$GITHUB_ACTIONS" != "true" ]; then
  exit 0
fi

sudo apt update
sudo apt install -y pandoc

PANVIMDOC="/tmp/panvimdoc"

git clone https://github.com/kdheepak/panvimdoc.git "$PANVIMDOC"

ME=$(pwd)

cd "$PANVIMDOC"

for f in "$ME"/docs/*.md; do
  ./panvimdoc.sh --project-name "snacks.nvim" --input-file "$f" --vim-version "Neovim" --demojify "true" >"$ME/doc/snacks.nvim-$(basename "$f" .md).txt"
done
